//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyam_Nyam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient_RecipeSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient_RecipeSteps()
        {
            this.RecipeSteps = new HashSet<RecipeSteps>();
        }
    
        public int Id { get; set; }
        public int IngredientId { get; set; }
        public int RecipesId { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeSteps> RecipeSteps { get; set; }
    }
}
