//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyam_Nyam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int Id { get; set; }
        public string ProcessDescription { get; set; }
        public string Time { get; set; }
        public Nullable<int> DishId { get; set; }
        public Nullable<int> IngredientI_RecipesId { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Ingredient_Recipes Ingredient_Recipes { get; set; }
    }
}
